# .streamlit/secrets.toml
[gcp_service_account]
type = "service_account"
project_id = "seu-project-id"
private_key_id = "chave-privada-id"
private_key = """
-----BEGIN PRIVATE KEY-----
SUA_CHAVE_PRIVADA_AQUI
-----END PRIVATE KEY-----
"""
client_email = "sua-conta-servico@seu-project.iam.gserviceaccount.com"
client_id = "123456789"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sua-conta-servico%40seu-project.iam.gserviceaccount.com"